name = "inkstone"
main = "src/worker/index.ts"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = [
  "/",
  "/index.html",
  "/api",
  "/api/*",
  "/s",
  "/s/*",
  "/authorize",
  "/authorize/*",
  "/oauth/*",
  "/mcp",
  "/mcp/*",
  "/.well-known/*",
]

[[d1_databases]]
binding = "DB"
database_name = "inkstone-db"
database_id = "5ee6a91f-edaa-49a1-b364-2519e9dc0408" #

[[kv_namespaces]]
binding = "FILES_KV"
id = "e5f2a1a9905b40e0a98188928a0e0aae"

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "87dc8a22e775418388619c1c0c0ee34e"

[[durable_objects.bindings]]
name = "SYNC_HUB"
class_name = "SyncHub"

[[durable_objects.bindings]]
name = "CREDENTIAL_VAULT"
class_name = "CredentialVault"

[exports.SyncHub]
type = "durable-object"
storage = "sqlite"

[exports.CredentialVault]
type = "durable-object"
storage = "sqlite"

[triggers]
crons = ["0 * * * *", "15,45 * * * *"]

[vars]
APP_NAME = "Inkstone"

[observability]
enabled = true

# 显式告诉 Wrangler 的打包工具如何解析 @shared 别名
[alias]
"@shared" = "./src/shared"

